### ISSUE TITLE
#1341 causes tests to fail

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1350]
On running tests locally, I receive the following error:

```
 FAIL  src/__tests__/algorithms/Bisection.test.js
  ● bisection › small cases

    TypeError: cmpToX is not a function

      13 |   if (hi <= lo) return lo;
      14 |   if (hi === lo + 1) {
    > 15 |     var c_1 = cmpToX(a[lo]);
         |               ^
      16 |     if (c_1 < 0) return hi;
      17 |     if (c_1 > 0) return lo;
      18 |     if (c_1 === 0 && findRightMost) return hi;

      at cmpToX (src/algorithms/Bisection.js:15:15)
      at Object.bisect (src/__tests__/algorithms/Bisection.test.js:6:12)

  ● bisection › duplicates

    TypeError: cmpToX is not a function

      20 |   }
      21 |   var mid = Math.floor((lo + hi) / 2.0);
    > 22 |   var c = cmpToX(a[mid]);
         |           ^
      23 |   if (c < 0 || (c === 0 && findRightMost)) {
      24 |     return bisect(a, x, cmpToX, mid + 1, hi, findRightMost);
      25 |   }

      at cmpToX (src/algorithms/Bisection.js:22:11)
      at Object.bisect (src/__tests__/algorithms/Bisection.test.js:44:12)
```

Seemingly triggered by the following line:

`expect(bisect([1], 1)).toBe(0);`

I have no idea why this isn't failing in production, since these passing tests just don't at all specify a "cmpToX" function

**Comment by anth-volk** [comment]
Appears to have been an issue with local config. Closing.
