### ISSUE TITLE
npm start syntax error on windows

### ISSUE THREAD

**Issue by kfoster19** [PolicyEngine/policyengine-app#20]
(base) PS C:\Users\Kevin\Documents\policyengine-app> npm start

> policyengine-app@0.1.0 start C:\Users\Kevin\Documents\policyengine-app     
> react-scripts start

C:\Users\Kevin\Documents\policyengine-app\node_modules\eslint-webpack-plugin\node_modules\jest-worker\build\index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) 
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Kevin\Documents\policyengine-app\node_modules\eslint-webpack-plugin\dist\getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! policyengine-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the policyengine-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kevin\AppData\Roaming\npm-cache\_logs\2022-12-01T23_18_10_489Z-debug.log

**Comment by MaxGhenis** [comment]
Might be a node version issue: https://stackoverflow.com/a/45108510/1840471

**Comment by anth-volk** [comment]
It's been a year and there have been no reports of this. Closing.
