### ISSUE TITLE
Analysis page crashes partway through generation

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#413]
https://www.loom.com/share/e61ceec8e47c426e856d2351deda9228

https://policyengine.org/us/policy?focus=policyOutput.analysis&reform=14&region=us&timePeriod=2023&baseline=2

Console:
```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading '0')
    at h3 (BlogPage.jsx:121:30)
    at ka (react-dom.production.min.js:167:137)
    at xs (react-dom.production.min.js:290:337)
    at yu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at ou (react-dom.production.min.js:271:88)
    at iu (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
    at MessagePort.M (scheduler.production.min.js:14:128)
fl @ react-dom.production.min.js:189
react-dom.production.min.js:283 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at h3 (BlogPage.jsx:121:30)
    at ka (react-dom.production.min.js:167:137)
    at xs (react-dom.production.min.js:290:337)
    at yu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at ou (react-dom.production.min.js:271:88)
    at iu (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
    at MessagePort.M (scheduler.production.min.js:14:128)
```

**Comment by nikhilwoodruff** [comment]
Right, so I guess it's producing invalid Markdown?

**Comment by nikhilwoodruff** [comment]
Haven't seen this at all in the last few months. But in theory could happen again, so leaving open but with low priority.
